window.OBEDGO_CONFIG={supabaseUrl:'https://qbwrfortjvzqtdiupgva.supabase.co',supabaseKey:'sb_publishable_jG63reY8x1wJbF3FGf9few_mcbZGDGU'};

async function obedgoPublicRpc(fn,body={}){const r=await fetch(OBEDGO_CONFIG.supabaseUrl+'/rest/v1/rpc/'+fn,{method:'POST',headers:{'Content-Type':'application/json','apikey':OBEDGO_CONFIG.supabaseKey,'Authorization':'Bearer '+OBEDGO_CONFIG.supabaseKey},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json()}

// Daily STOP: user screen. Existing orders are preserved; only new saving is blocked server-side.
window.addEventListener('load',()=>setTimeout(async()=>{
  if(!document.getElementById('save'))return;
  try{const st=await obedgoPublicRpc('get_ordering_status');if(!st.closed)return;const status=document.getElementById('status'),save=document.getElementById('save'),add=document.getElementById('add'),cancel=document.getElementById('cancel');if(status){status.style.display='block';status.style.background='#fef2f2';status.style.borderColor='#fecaca';status.innerHTML='<b>🔴 DNES MIMO PREVÁDZKY</b><br>Objednávanie obedov je dnes uzavreté.'}if(save){save.disabled=true;save.textContent='DNES MIMO PREVÁDZKY'}if(add)add.disabled=true;if(cancel)cancel.style.display='none';document.querySelectorAll('#items input, input[name="pay"]').forEach(x=>x.disabled=true)}catch(e){console.error('Ordering status',e)}
},250));

// Admin daily STOP / OPEN control. It applies only to the current Bratislava calendar date.
window.addEventListener('load',()=>setTimeout(()=>{
  const dash=document.getElementById('dash');if(!dash)return;
  const top=dash.querySelector('.top');if(!top||document.getElementById('dailyStop'))return;
  const wrap=document.createElement('div');wrap.id='dailyStop';wrap.style.cssText='width:100%;margin-top:12px;padding:14px;border:1px solid #e0e6ef;border-radius:15px;background:#f7f9fc';
  wrap.innerHTML='<div id="dailyStopState" style="font-weight:900;margin-bottom:8px">Načítavam stav objednávania…</div><button id="dailyStopBtn" class="btn" style="margin:0;background:#b42318">🔴 UZAVRIEŤ OBJEDNÁVANIE NA DNES</button>';
  top.insertAdjacentElement('afterend',wrap);
  async function refreshStop(){try{const st=await obedgoPublicRpc('get_ordering_status');const state=document.getElementById('dailyStopState'),btn=document.getElementById('dailyStopBtn');state.textContent=st.closed?'🔴 Dnes mimo prevádzky':'🟢 Dnes je objednávanie povolené';btn.dataset.closed=st.closed?'1':'0';btn.textContent=st.closed?'🟢 OTVORIŤ OBJEDNÁVANIE':'🔴 UZAVRIEŤ OBJEDNÁVANIE NA DNES';btn.style.background=st.closed?'#15803d':'#b42318'}catch(e){console.error(e)}}
  document.getElementById('dailyStopBtn').onclick=async function(){const pin=document.getElementById('pin')?.value.trim();if(!pin||pin.length!==6){alert('Najprv sa prihlás do Adminu.');return}const closing=this.dataset.closed!=='1';if(closing&&!confirm('Uzavrieť objednávanie na dnešný deň? Existujúce objednávky zostanú zachované.'))return;this.disabled=true;try{await obedgoPublicRpc('set_ordering_closed',{p_pin:pin,p_closed:closing});await refreshStop()}catch(e){alert('Zmenu sa nepodarilo uložiť. Skontroluj Admin PIN.');console.error(e)}finally{this.disabled=false}};
  refreshStop();
},300));

// Do not show the temporary/invalid payment QR. Keep bank transfer and IBAN available.
window.addEventListener('load',()=>setTimeout(()=>{const qr=document.querySelector('#paymentQr img'),title=document.querySelector('#paymentQr .title'),hint=document.querySelector('#paymentQr .hint');if(qr)qr.style.display='none';if(title)title.textContent='Číslo účtu pre prevod';if(hint)hint.textContent='Sumu zadaj podľa počtu objednaných obedov.'},100));

(function(){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Bratislava',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).map(x=>[x.type,x.value]));const today=`${p.year}-${p.month}-${p.day}`;const hour=Number(p.hour);function add(s,n){let a=s.split('-').map(Number),d=new Date(Date.UTC(a[0],a[1]-1,a[2]+n));return d.toISOString().slice(0,10)}function wd(s){let a=s.split('-').map(Number);return new Date(Date.UTC(a[0],a[1]-1,a[2])).getUTCDay()}function next(s){do{s=add(s,1)}while(wd(s)==0||wd(s)==6);return s}let day=wd(today),weekend=day==0||day==6,evening=hour>=17,early=hour<7,preview=evening||early||weekend;if(!preview)return;let target;if(weekend){target=day==6?add(today,2):add(today,1)}else if(evening){target=next(today)}else{target=today}window.OBEDGO_PREVIEW_MODE=true;const nf=window.fetch.bind(window);window.fetch=function(i,o){let u=typeof i==='string'?i:i.url;if(u.includes('/rest/v1/daily_menu?')){let x=new URL(u,location.href);x.searchParams.set('menu_date','eq.'+target);return nf(x.toString(),o)}if(u.includes('/rest/v1/rpc/get_my_order'))return Promise.resolve(new Response('null',{status:200,headers:{'Content-Type':'application/json'}}));return nf(i,o)};window.addEventListener('load',()=>setTimeout(()=>{let s=document.getElementById('status'),b=document.getElementById('save'),c=document.getElementById('cancel'),n=document.querySelector('.notice');if(s){s.style.display='block';s.innerHTML='<b>👀 NÁHĽAD NA ĎALŠÍ PRACOVNÝ DEŇ</b><br>Objednávanie bude možné od 07:00 do 09:15.'}if(b){b.disabled=true;b.textContent='NÁHĽAD MENU'}if(c)c.style.display='none';if(n)n.textContent='Objednávanie je možné od 07:00 do 09:15. Po 17:00 ObedGo zobrazuje menu na nasledujúci pracovný deň.'},800))})();